# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FakeShop' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FakeShop

  target 'FakeShopTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'FSPagerView'
    pod 'Kingfisher', '~> 7.0'
    
  end

  target 'FakeShopUITests' do
    # Pods for testing
  end

end
